#This workflow requires a file named NewestRelease.json in the main .csproj folder
# that matches the schema at https://github.com/Pistachio-dev/Workflows/blob/master/Schemas/NewestReleaseSchema.json
# It is intended to be called from each plugin repository
name: "Manual remote release"
on:
  workflow_call:
    inputs:
      internalPluginName:
        required: true
        type: string
      target_repo: # github.action_repository, except if releasing on a different repo. Eg Pistachio-dev/WorkflowsTestReleaseOnly
        required: true 
        type: string
    secrets:
      token: #Usually "secrets.GITHUB_TOKEN", but sometimes you'll need a fine grained personal one
        required: true
env:
  internalPluginName: ${{inputs.internalPluginName}}  # Set this to the assembly name of the plugin to process
  target_repo: ${{ inputs.target_repo }} # Change this if releasing on a different repo. Eg Pistachio-dev/WorkflowsTestReleaseOnly
  token: ${{secrets.token}} # You'll need a special token with permissions on that repo
  internalPluginVersion: "0.0.0.0" # Set by the "Get version number" step
  tag: "unset_tag" # Set by the "Retrieve data for release" step
jobs:
  releasePluginUpdate: 
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Copy powershell scripts to the current folder # They won't be commited
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/Pistachio-dev/Workflows/refs/heads/master/.github/workflows/powershellScripts.zip -OutFile powershellScripts.zip -RetryIntervalSec 20 -MaximumRetryCount 10
          Expand-Archive -Force powershellScripts.zip .github.\workflows\
      - name: "Verify version information"
        run: .\.github\Workflows\UpdateVersions.ps1 -PluginAssemblyName "${{env.internalPluginName}}"
      - name: "Get version number"
        run: |
            $versionRetrieved = .\.github\Workflows\GetVersionNumber.ps1 -PluginAssemblyName "${{env.internalPluginName}}"
            echo "internalPluginVersion=$versionRetrieved" >> $env:GITHUB_ENV
      - name: "Debug that we have the correct version"
        run: Write-Output "${{env.internalPluginVersion}}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip -RetryIntervalSec 20 -MaximumRetryCount 10
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Build
        run: |
          $ver = "${{env.internalPluginVersion}}"
          Write-Output "Version: $($ver)"
          invoke-expression 'dotnet build --no-restore --configuration Release --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver'
      - name: Archive (move the dalamud packager artifact somewhere easier to access)
        run: Copy-Item -Path ${{env.internalPluginName}}/bin/x64/Release/${{env.internalPluginName}} -Destination ${{env.internalPluginName}}.zip
      - name: Retrieve data for release
        run: |
          $localPatchNotes = "$(.\.github\Workflows\GetChangeLog.ps1 -PluginAssemblyName ${{env.internalPluginName}})"
          Set-Content -Path ".\PatchNotes.txt" -Value $localPatchNotes
          $localTag = "$(.\.github\Workflows\GetTag.ps1 -PluginAssemblyName ${{env.internalPluginName}})"
          Write-Output "Local tag: $($localTag)"
          "tag=$localTag" >> $env:GITHUB_ENV
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: latest.zip
          body_path: .\PatchNotes.txt
          tag_name: ${{env.tag}}
          make_latest: $true
          repository: ${{ env.target_repo }}
          token: ${{env.token}}
      - name: Update downloads and timestamp
        run: |
          # inlinining the whole thing because it would not take an url as parameter no matter what, so screw it
          $zipDownloadURL = ${{toJson(fromJson(steps.release.outputs.assets)[0].browser_download_url)}}
          Write-Output "Download URL is $($zipDownloadUrl)"
          $basePluginFolderPath = "${{env.internalPluginName}}\"
          $newestReleasePath = "$($basePluginFolderPath)NewestRelease.json"

          $newestReleaseData = Get-Content $newestReleasePath | ConvertFrom-Json

          $repoPath = "Repo.json";
          $repoArray = Get-Content $repoPath | ConvertFrom-Json
          $repoData = $repoArray | Select-Object -Index 0

          if ($newestReleaseData.IsTest){
              $repoData | Add-Member -NotePropertyName "DownloadLinkTesting" -NotePropertyValue $zipDownloadURL -Force
              Write-Output "Download link set for testing"
          }
          else{
              $repoData | Add-Member -NotePropertyName "DownloadLinkInstall" -NotePropertyValue $zipDownloadURL -Force
              $repoData | Add-Member -NotePropertyName "DownloadLinkUpdate" -NotePropertyValue $zipDownloadURL -Force
              Write-Output "Download link set for install and update"
          }
          
          $utcDate = Get-Date -AsUTC
          $timeStamp = [int]([Math]::Floor($utcDate.Subtract([DateTime]::UnixEpoch).TotalSeconds))

          $repoData | Add-Member "LastUpdate" -NotePropertyValue $timeStamp -Force

          Set-Content -Path $repoPath -Value (ConvertTo-Json @($repoArray))

          # Clear the changelog from NewestRelease.json on a successful non-test release
          if ($newestReleaseData.IsTest -eq $false){
            $newestReleaseData | Add-Member "ChangeLog" -NotePropertyValue ""  -Force
            Set-Content -Path $newestReleasePath -Value (ConvertTo-Json $newestReleaseData)
          }
      - name: Commit Repo.json and ChangeLog.json
        run: |
          $basePluginFolderPath = "${{env.internalPluginName}}\"
          git config --local user.name "[bot]github-actions_manual-release"
          git config --local user.email "[bot]github-actions_manual-release@users.noreply.github.com"
          git add "Repo.json"
          git add "$($basePluginFolderPath)ChangeLog.json"
          # git commit -m "[CI] Updating Repo.json and ChangeLog.json for new release"
          # git push origin master
      - name: Copy Repo.json to public repository
        if: env.target_repo != github.action_repository  
        uses: actions/checkout@v2
        with:
          token: ${{env.token}}
          repository: ${{env.target_repo}}
          path: "..\\holdem_public_repo"
      - name: Debug file structure
        run: |
          Get-ChildItem -Path ..\.. -Recurse -Depth 4
          Write-Output ${{github.action_repository}}
      - name: Copy Repo.json to public repo and commit
        if: env.target_repo != github.action_repository  
        run: |          
          Copy-Item -Path Repo.json -Destination "..\\holdem_public_repo\\Repo.json"
      - name: Push updated repo
        if: env.target_repo != github.action_repository  
        run: |
          git config --local user.name "[bot]github-actions_manual-release"
          git config --local user.email "[bot]github-actions_manual-release@users.noreply.github.com"
          git add "Repo.json"
          git commit -m "[CI] Updating Repo.json for new release"
          git push origin

        
          




